### ISSUE TITLE
doubt - reward 

### ISSUE THREAD

**Issue by FibraLogica** [Mobius1/esx_collectables#3]
Thx for your script, is very good... 

but tell me, is possible reward the player with an item after the mission is complete???
i really need your help!
💯

**Comment by Mobius1** [comment]
You can listen for the client event `esx_collectables:questCompleted`:

```lua
AddEventHandler('esx_collectables:questCompleted', function(group)
    -- do something when player has found all collectables in the group
end)
```

Make sure you have the [latest version](https://github.com/Mobius1/esx_collectables/releases/tag/1.2.0) installed.
